[bar/main]
width = 100%
height = 25
background = #aa1a1a2e
foreground = #ffffff
font-0 = monospace:size=9
font-1 = Noto Color Emoji:scale=8

padding-left = 1
padding-right = 1

module-margin-left = 1
module-margin-right = 1

#separator = |
#separator-foreground = #555555

modules-left = i3 title
modules-center = date
modules-right = spotify separador volume separador2 memory separador2 cpu separador

[module/separador]
type = custom/text
content = "    "

[module/separador2]
type = custom/text
content = "  "


[module/i3]
type = internal/i3

label-focused = %name%
label-focused-foreground = #f0c040
label-focused-padding = 1

label-unfocused = %name%
label-unfocused-foreground = #888888
label-unfocused-padding = 1

label-separator = " "

[module/title]
type = internal/xwindow
label = %title%
label-maxlen = 40
label-foreground = #aaaaaa

[module/date]
type = internal/date
interval = 1
date = %A %d %b
time = %H:%M
label = %{F#aaaaaa}%date%%{F-}  %{F#ffffff}%time%%{F-}

[module/memory]
type = internal/memory
interval = 2
label = %{F#aaaaaa}RAM%{F-} %{F#f0c040}%percentage_used%%%{F-}

[module/cpu]
type = internal/cpu
interval = 2
label = %{F#aaaaaa}CPU%{F-} %{F#f0c040}%percentage%%%{F-}

[module/volume]
type = internal/pulseaudio
label-volume = %{F#aaaaaa}VOL%{F-} %{F#f0c040}%percentage%%%{F-}
label-muted = %{F#888888}VOL mute%{F-}

[module/spotify]
type = custom/script
exec = playerctl metadata --format "{{ artist }} - {{ title }}" 2>/dev/null
interval = 2
click-left = playerctl previous
click-right = playerctl next
click-middle = playerctl play-pause
